apiVersion: v1
kind: Pod
metadata:
  name: tpu-orchestrator
  labels:
    app: tpu-orchestrator
spec:
  serviceAccountName: snapshot-agent
  containers:
    - name: orchestrator
      image: us-west1-docker.pkg.dev/aishuk-test/tpu-poc-repo/tpu-orchestrator:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 9000
          name: http
      env:
        - name: MODE
          value: "snapshot"
        - name: ORCH_PORT
          value: "9000"
        - name: SNAPSHOT_AGENT_PORT
          value: "9001"
      readinessProbe:
        httpGet:
          path: /health
          port: 9000
        initialDelaySeconds: 5
        periodSeconds: 10
  restartPolicy: Never
